// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sentinel-homepage/EditorialSophistication.tsx": () => import("../components/mockups/sentinel-homepage/EditorialSophistication.tsx"),
  "./components/mockups/sentinel-homepage/IceProtocol.tsx": () => import("../components/mockups/sentinel-homepage/IceProtocol.tsx"),
  "./components/mockups/sentinel-homepage/MidnightInk.tsx": () => import("../components/mockups/sentinel-homepage/MidnightInk.tsx"),
  "./components/mockups/sentinel-homepage/ParchmentNoir.tsx": () => import("../components/mockups/sentinel-homepage/ParchmentNoir.tsx"),
  "./components/mockups/sentinel-homepage/StarkPolished.tsx": () => import("../components/mockups/sentinel-homepage/StarkPolished.tsx"),
  "./components/mockups/sentinel-homepage/StarkPrecision.tsx": () => import("../components/mockups/sentinel-homepage/StarkPrecision.tsx"),
  "./components/mockups/sentinel-homepage/StarkTight.tsx": () => import("../components/mockups/sentinel-homepage/StarkTight.tsx"),
  "./components/mockups/sentinel-homepage/WarmAuthority.tsx": () => import("../components/mockups/sentinel-homepage/WarmAuthority.tsx")
};
